var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/user/my-drive/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0ef7f6f._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_919b5801._.js")
R.c("server/chunks/ssr/[root-of-the-server]__71dbd6ef._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__f0180254._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_user_my-drive_page_actions_c2ae5f0f.js")
R.m(49538)
module.exports=R.m(49538).exports
